version: "3.9"
services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=shelter-app
      - POSTGRES_PASSWORD=shelter-app
      - POSTGRES_DB=shelter-app

  api:
    build: .
    command: uvicorn src.main:app --reload --host=0.0.0.0 --port=8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://shelter-app:shelter-app@db:5432/shelter-app
      - DEBUG=True
      - INVENTORY_SERVICE_URL=http://changeme:8001
      - NOTIFICATION_SERVICE_URL=http://changeme:8002
