"""create inital tables

Revision ID: 123e034621dc
Revises: 
Create Date: 2022-05-09 21:35:27.372118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '123e034621dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
