"""create dog table

Revision ID: 2b5f78b4d5ad
Revises: 123e034621dc
Create Date: 2022-05-09 21:44:37.831075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b5f78b4d5ad'
down_revision = '123e034621dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
