"""create dog table1

Revision ID: 3421c10dc81e
Revises: 2b5f78b4d5ad
Create Date: 2022-05-09 21:47:18.226156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3421c10dc81e'
down_revision = '2b5f78b4d5ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
