"""create dogs table

Revision ID: 6e0dd0105824
Revises: 
Create Date: 2022-05-15 21:20:36.287896

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6e0dd0105824"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dogs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("image_url", sa.String(length=255), nullable=True),
        sa.Column("is_chipped", sa.Boolean(), nullable=True),
        sa.Column("coordinates", sa.String(length=255), nullable=True),
        sa.Column(
            "breed",
            postgresql.ENUM(
                "MALTESE",
                "CORGI",
                "POODLE",
                "PUG",
                "BICHON",
                "POMERANIAN",
                "BOXER",
                name="breeds",
            ),
            nullable=False,
        ),
        sa.Column(
            "dog_status",
            postgresql.ENUM(
                "LOST", "WAITING", "SHELTERED", "RESERVED", "RESCUED", name="statuses"
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dogs")
    # ### end Alembic commands ###
