"""create dog table2

Revision ID: db882ccbd9e3
Revises: 3421c10dc81e
Create Date: 2022-05-09 21:55:46.969009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db882ccbd9e3'
down_revision = '3421c10dc81e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
